name: Test on Pull Request
on: pull_request
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - name: Run Kotlin Linter
        run: .\gradlew ktlintStagingDebugCheck
      
      - name: Run Unit Test
        run: ./gradlew testDebugUnitTest