name: Test on Pull Request
on: [pull_request]
jobs:
  #lint:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v3
#
  #    - uses: actions/setup-java@v3
  #      with:
  #        distribution: 'zulu'
  #        java-version: '11'
  #        cache: gradle
#
  #    - name: ktlint
  #      uses: ScaCap/action-ktlint@master
  #      with:
  #        github_token: ${{ secrets.github_token }}
  #        reporter: github-pr-review # Change reporter
  run-unit-test:
    #needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #- name: install microk8s
      #  uses: balchua/microk8s-actions@v0.2.1
      #  with:
      #    channel: ${{ matrix.microk8s-version }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: RUnit Test
        run: ./gradlew testDebugUnitTest
        continue-on-error: true

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
